import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/NavBar";
import CartProvider from "./providers/CartProviders";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster toastOptions={{style:{
          background:"rgb(51 65 85)",
          color:"#fff"
        }}}/>
        <CartProvider>
       <div className="flex flex-col h-screen   ">
          <NavBar/>
          <main className="flex grow "> {children}</main>
          <Footer/>
       </div>
        </CartProvider>
        
        </body>
    </html>
  );
}
